--------------------------------------------------------------------------------
-- ddl_marketplace.sql
-- C2C Marketplace 신규 테이블 DDL (Oracle, 스키마 TOYCHAT 또는 별도 테스트 스키마)
--
-- 기준 문서 : docs/4. 프로젝트고도화/3. C2C_Marketplace_설계_명세서.md 4.2절(2.1판)
-- 실행 계정 : 테이블을 만들 스키마의 계정 본인
-- 선행 조건 : ddl_toychat.sql 의 MEMBERTBL 이 먼저 존재하고 ID 에 기본키(PK_MEMBERTBL)가 있어야 한다(회원 FK 대상). 기본키가 없으면 ORA-02270 이 난다(판단 기록 J-30).
--
-- 작성 규칙
--   1) ddl-auto: none 이므로 Hibernate 는 이 스크립트를 실행하지 않는다.
--      엔티티의 @Table/@Column 이름과 아래 식별자가 그대로 일치해야 한다.
--   2) 식별자는 따옴표 없는 대문자로 쓴다(ddl_toychat.sql 과 같은 규칙).
--   3) 숫자 PK 는 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY, 금액은 NUMBER(15),
--      수량은 NUMBER(10), 시각은 TIMESTAMP(6)(UTC 값 저장), 열거형은 VARCHAR2(30).
--   4) FK 는 회원·상품·대화·주문과 적용 제안에 대한 참조에만 둔다(설계 4.1·4.2).
--   5) 동시 요청을 막기 위한 UNIQUE 제약과 성능 목적의 인덱스는 이번 범위에서 두지 않는다
--      (설계 1.1·4.1). SHIPMENT·REFUND_REQUEST 의 "주문당 하나" 규칙은 순차 요청에서
--      서비스의 현재 상태 검사로 지킨다.
--   6) 시각 사이의 관계(예: INSPECTION_DEADLINE_AT = DELIVERED_AT + 48시간)는
--      애플리케이션이 계산해서 저장하며 CHECK 제약으로 두지 않는다.
--
-- 실행 순서 : 부모 → 자식
--   1) PRODUCT  2) WALLET  3) CONVERSATION  4) PRICE_OFFER  5) PURCHASE_ORDER
--   6) SHIPMENT  7) REFUND_REQUEST  8) CHAT_MESSAGE  9) BALANCE_TRANSACTION
--
-- 되돌리기 : 아래 [DROP] 블록을 자식 → 부모 순서로 실행한다. 기존 테이블은 건드리지 않는다.
--------------------------------------------------------------------------------


--==============================================================================
-- [DROP] 재실행용 — 필요할 때만 주석 해제 (자식 → 부모 순서)
--==============================================================================
-- DROP TABLE BALANCE_TRANSACTION CASCADE CONSTRAINTS PURGE;
-- DROP TABLE CHAT_MESSAGE CASCADE CONSTRAINTS PURGE;
-- DROP TABLE REFUND_REQUEST CASCADE CONSTRAINTS PURGE;
-- DROP TABLE SHIPMENT CASCADE CONSTRAINTS PURGE;
-- DROP TABLE PURCHASE_ORDER CASCADE CONSTRAINTS PURGE;
-- DROP TABLE PRICE_OFFER CASCADE CONSTRAINTS PURGE;
-- DROP TABLE CONVERSATION CASCADE CONSTRAINTS PURGE;
-- DROP TABLE WALLET CASCADE CONSTRAINTS PURGE;
-- DROP TABLE PRODUCT CASCADE CONSTRAINTS PURGE;


--==============================================================================
-- 1) PRODUCT  (엔티티: com.chatservice.marketplace.product.domain.Product)
--    판매 등록 건. 등록 후 상품 정보와 최초 수량은 바꾸지 않고, 결제 성공 시
--    남은 수량만 줄인다. 남은 수량이 0이 되면 SOLD 로 바뀌며 다시 ON_SALE 로 돌아가지 않는다.
--==============================================================================
CREATE TABLE PRODUCT (
    PRODUCT_ID          NUMBER(19)          GENERATED BY DEFAULT AS IDENTITY,
    SELLER_ID           VARCHAR2(255)       NOT NULL,
    NAME                VARCHAR2(100 CHAR)  NOT NULL,
    DESCRIPTION         CLOB                NOT NULL,
    CATEGORY            VARCHAR2(30)        NOT NULL,
    PRICE               NUMBER(15)          NOT NULL,
    INITIAL_QUANTITY    NUMBER(10)          NOT NULL,
    REMAINING_QUANTITY  NUMBER(10)          NOT NULL,
    STATUS              VARCHAR2(30)        DEFAULT 'ON_SALE' NOT NULL,
    CREATED_AT          TIMESTAMP(6)        NOT NULL,
    SOLD_AT             TIMESTAMP(6),
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT FK_PRODUCT_SELLER FOREIGN KEY (SELLER_ID) REFERENCES MEMBERTBL (ID),
    CONSTRAINT CK_PRODUCT_CATEGORY CHECK (CATEGORY IN ('CLOTHING_ACCESSORIES', 'LIVING', 'ELECTRONICS', 'BOOKS_HOBBY', 'ETC')),
    CONSTRAINT CK_PRODUCT_PRICE CHECK (PRICE > 0),
    CONSTRAINT CK_PRODUCT_INITIAL_QTY CHECK (INITIAL_QUANTITY >= 1),
    CONSTRAINT CK_PRODUCT_REMAINING_QTY CHECK (REMAINING_QUANTITY >= 0 AND REMAINING_QUANTITY <= INITIAL_QUANTITY),
    CONSTRAINT CK_PRODUCT_STATUS CHECK (STATUS IN ('ON_SALE', 'SOLD'))
);


--==============================================================================
-- 2) WALLET  (엔티티: com.chatservice.marketplace.wallet.domain.Wallet)
--    회원과 1:1. 최초 충전·최초 조회·최초 판매대금 지급 시 잔액 0으로 만든다.
--    BALANCE >= 0 은 "잔액을 초과해 구매할 수 없다"(BR-003)를 데이터 수준에서 표현한다.
--==============================================================================
CREATE TABLE WALLET (
    MEMBER_ID   VARCHAR2(255)   NOT NULL,
    BALANCE     NUMBER(15)      DEFAULT 0 NOT NULL,
    UPDATED_AT  TIMESTAMP(6)    NOT NULL,
    CONSTRAINT PK_WALLET PRIMARY KEY (MEMBER_ID),
    CONSTRAINT FK_WALLET_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERTBL (ID),
    CONSTRAINT CK_WALLET_BALANCE CHECK (BALANCE >= 0)
);


--==============================================================================
-- 3) CONVERSATION  (엔티티: com.chatservice.marketplace.conversation.domain.Conversation)
--    상품 하나와 구매 희망자 하나의 조합에 대화 하나. 순차 요청에서는 조회 후 생성으로 지킨다.
--    쓰기 가능 여부는 저장하지 않고 상품·주문 상태로 계산한다.
--==============================================================================
CREATE TABLE CONVERSATION (
    CONVERSATION_ID     NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    PRODUCT_ID          NUMBER(19)      NOT NULL,
    BUYER_ID            VARCHAR2(255)   NOT NULL,
    SELLER_ID           VARCHAR2(255)   NOT NULL,
    CREATED_AT          TIMESTAMP(6)    NOT NULL,
    CREATED_BY_SYSTEM   NUMBER(1)       DEFAULT 0 NOT NULL,
    CONSTRAINT PK_CONVERSATION PRIMARY KEY (CONVERSATION_ID),
    CONSTRAINT FK_CONVERSATION_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID),
    CONSTRAINT FK_CONVERSATION_BUYER FOREIGN KEY (BUYER_ID) REFERENCES MEMBERTBL (ID),
    CONSTRAINT FK_CONVERSATION_SELLER FOREIGN KEY (SELLER_ID) REFERENCES MEMBERTBL (ID),
    CONSTRAINT CK_CONVERSATION_SYSTEM CHECK (CREATED_BY_SYSTEM IN (0, 1))
);


--==============================================================================
-- 4) PRICE_OFFER  (엔티티: com.chatservice.marketplace.offer.domain.PriceOffer)
--    "등록 가격보다 작음" 조건은 다른 테이블 값과의 비교라 서비스에서 검사한다.
--==============================================================================
CREATE TABLE PRICE_OFFER (
    OFFER_ID         NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    CONVERSATION_ID  NUMBER(19)      NOT NULL,
    PRODUCT_ID       NUMBER(19)      NOT NULL,
    BUYER_ID         VARCHAR2(255)   NOT NULL,
    SELLER_ID        VARCHAR2(255)   NOT NULL,
    AMOUNT           NUMBER(15)      NOT NULL,
    STATUS           VARCHAR2(30)    DEFAULT 'PENDING' NOT NULL,
    REQUEST_ID       VARCHAR2(64),
    CREATED_AT       TIMESTAMP(6)    NOT NULL,
    RESPONDED_AT     TIMESTAMP(6),
    CONSTRAINT PK_PRICE_OFFER PRIMARY KEY (OFFER_ID),
    CONSTRAINT FK_PRICE_OFFER_CONVERSATION FOREIGN KEY (CONVERSATION_ID) REFERENCES CONVERSATION (CONVERSATION_ID),
    CONSTRAINT FK_PRICE_OFFER_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID),
    CONSTRAINT FK_PRICE_OFFER_BUYER FOREIGN KEY (BUYER_ID) REFERENCES MEMBERTBL (ID),
    CONSTRAINT FK_PRICE_OFFER_SELLER FOREIGN KEY (SELLER_ID) REFERENCES MEMBERTBL (ID),
    CONSTRAINT CK_PRICE_OFFER_AMOUNT CHECK (AMOUNT > 0),
    CONSTRAINT CK_PRICE_OFFER_STATUS CHECK (STATUS IN ('PENDING', 'ACCEPTED', 'REJECTED'))
);


--==============================================================================
-- 5) PURCHASE_ORDER  (엔티티: com.chatservice.marketplace.order.domain.PurchaseOrder)
--    ORDER 는 Oracle 예약어라서 PURCHASE_ORDER 로 한다.
--    한 상품에 여러 주문, 같은 구매자의 별도 주문, 한 수락 제안의 여러 주문 재사용을 허용하므로
--    PRODUCT_ID·OFFER_ID 에 UNIQUE 를 두지 않는다.
--    취소는 배송 상태가 아니라 거래 결과(TRADE_STATUS = CANCELLED)로 저장한다.
--==============================================================================
CREATE TABLE PURCHASE_ORDER (
    ORDER_ID                NUMBER(19)          GENERATED BY DEFAULT AS IDENTITY,
    PRODUCT_ID              NUMBER(19)          NOT NULL,
    BUYER_ID                VARCHAR2(255)       NOT NULL,
    SELLER_ID               VARCHAR2(255)       NOT NULL,
    QUANTITY                NUMBER(10)          NOT NULL,
    UNIT_PRICE              NUMBER(15)          NOT NULL,
    PAID_AMOUNT             NUMBER(15)          NOT NULL,
    PRICE_SOURCE            VARCHAR2(30)        NOT NULL,
    OFFER_ID                NUMBER(19),
    RECIPIENT_NAME          VARCHAR2(100 CHAR)  NOT NULL,
    SHIPPING_ADDRESS        VARCHAR2(500 CHAR)  NOT NULL,
    SHIPPING_STATUS         VARCHAR2(30)        DEFAULT 'WAITING_SHIPMENT' NOT NULL,
    TRADE_STATUS            VARCHAR2(30)        DEFAULT 'IN_PROGRESS' NOT NULL,
    COMPLETION_CAUSE        VARCHAR2(30),
    CONFIRMED_AT            TIMESTAMP(6)        NOT NULL,
    SHIP_DEADLINE_AT        TIMESTAMP(6)        NOT NULL,
    DELIVERED_AT            TIMESTAMP(6),
    INSPECTION_DEADLINE_AT  TIMESTAMP(6),
    FINALIZED_AT            TIMESTAMP(6),
    CANCELLED_BY            VARCHAR2(30),
    CANCEL_REASON           VARCHAR2(500 CHAR),
    REQUEST_ID              VARCHAR2(64),
    CONSTRAINT PK_PURCHASE_ORDER PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_PURCHASE_ORDER_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID),
    CONSTRAINT FK_PURCHASE_ORDER_BUYER FOREIGN KEY (BUYER_ID) REFERENCES MEMBERTBL (ID),
    CONSTRAINT FK_PURCHASE_ORDER_SELLER FOREIGN KEY (SELLER_ID) REFERENCES MEMBERTBL (ID),
    CONSTRAINT FK_PURCHASE_ORDER_OFFER FOREIGN KEY (OFFER_ID) REFERENCES PRICE_OFFER (OFFER_ID),
    CONSTRAINT CK_PURCHASE_ORDER_QUANTITY CHECK (QUANTITY >= 1),
    CONSTRAINT CK_PURCHASE_ORDER_UNIT_PRICE CHECK (UNIT_PRICE > 0),
    CONSTRAINT CK_PURCHASE_ORDER_PAID_AMOUNT CHECK (PAID_AMOUNT = UNIT_PRICE * QUANTITY),
    CONSTRAINT CK_PURCHASE_ORDER_PRICE_SOURCE CHECK (PRICE_SOURCE IN ('LISTED', 'AGREED')),
    CONSTRAINT CK_PURCHASE_ORDER_SHIPPING CHECK (SHIPPING_STATUS IN ('WAITING_SHIPMENT', 'SHIPPING', 'DELIVERED')),
    CONSTRAINT CK_PURCHASE_ORDER_TRADE CHECK (TRADE_STATUS IN ('IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'REFUNDED', 'CANCELLED')),
    CONSTRAINT CK_PURCHASE_ORDER_CAUSE CHECK (COMPLETION_CAUSE IS NULL OR COMPLETION_CAUSE IN ('BUYER_CONFIRMED', 'AUTO_EXPIRED', 'REFUND_REJECTED')),
    CONSTRAINT CK_PURCHASE_ORDER_CANCELLED_BY CHECK (CANCELLED_BY IS NULL OR CANCELLED_BY IN ('BUYER', 'SELLER', 'SYSTEM'))
);


--==============================================================================
-- 6) SHIPMENT  (엔티티: com.chatservice.marketplace.order.domain.Shipment)
--    행이 있다는 것 자체가 발송되었다는 사실이다. 수정·삭제·재등록 기능은 없다.
--==============================================================================
CREATE TABLE SHIPMENT (
    SHIPMENT_ID      NUMBER(19)          GENERATED BY DEFAULT AS IDENTITY,
    ORDER_ID         NUMBER(19)          NOT NULL,
    CARRIER_NAME     VARCHAR2(100 CHAR)  NOT NULL,
    TRACKING_NUMBER  VARCHAR2(100 CHAR)  NOT NULL,
    SHIPPED_AT       TIMESTAMP(6)        NOT NULL,
    DELIVERY_DUE_AT  TIMESTAMP(6)        NOT NULL,
    REQUEST_ID       VARCHAR2(64),
    CONSTRAINT PK_SHIPMENT PRIMARY KEY (SHIPMENT_ID),
    CONSTRAINT FK_SHIPMENT_ORDER FOREIGN KEY (ORDER_ID) REFERENCES PURCHASE_ORDER (ORDER_ID)
);


--==============================================================================
-- 7) REFUND_REQUEST  (엔티티: com.chatservice.marketplace.order.domain.RefundRequest)
--    주문당 유효한 요청 하나. 수정·철회 기능은 없다.
--==============================================================================
CREATE TABLE REFUND_REQUEST (
    REFUND_REQUEST_ID     NUMBER(19)           GENERATED BY DEFAULT AS IDENTITY,
    ORDER_ID              NUMBER(19)           NOT NULL,
    BUYER_ID              VARCHAR2(255)        NOT NULL,
    REASON_CODE           VARCHAR2(30)         NOT NULL,
    DETAIL                VARCHAR2(2000 CHAR)  NOT NULL,
    DECISION              VARCHAR2(30)         DEFAULT 'PENDING' NOT NULL,
    REQUESTED_AT          TIMESTAMP(6)         NOT NULL,
    RESPONSE_DEADLINE_AT  TIMESTAMP(6)         NOT NULL,
    DECIDED_AT            TIMESTAMP(6),
    REQUEST_ID            VARCHAR2(64),
    CONSTRAINT PK_REFUND_REQUEST PRIMARY KEY (REFUND_REQUEST_ID),
    CONSTRAINT FK_REFUND_REQUEST_ORDER FOREIGN KEY (ORDER_ID) REFERENCES PURCHASE_ORDER (ORDER_ID),
    CONSTRAINT FK_REFUND_REQUEST_BUYER FOREIGN KEY (BUYER_ID) REFERENCES MEMBERTBL (ID),
    CONSTRAINT CK_REFUND_REQUEST_REASON CHECK (REASON_CODE IN ('DESCRIPTION_MISMATCH')),
    CONSTRAINT CK_REFUND_REQUEST_DECISION CHECK (DECISION IN ('PENDING', 'APPROVED', 'REJECTED', 'AUTO_APPROVED'))
);


--==============================================================================
-- 8) CHAT_MESSAGE  (엔티티: com.chatservice.marketplace.conversation.domain.ChatMessage)
--    한 대화 안의 조회 순서는 MESSAGE_ID 오름차순이다.
--==============================================================================
CREATE TABLE CHAT_MESSAGE (
    MESSAGE_ID         NUMBER(19)           GENERATED BY DEFAULT AS IDENTITY,
    CONVERSATION_ID    NUMBER(19)           NOT NULL,
    SENDER_ID          VARCHAR2(255)        NOT NULL,
    CONTENT            VARCHAR2(1000 CHAR)  NOT NULL,
    CLIENT_MESSAGE_ID  VARCHAR2(64),
    CREATED_AT         TIMESTAMP(6)         NOT NULL,
    CONSTRAINT PK_CHAT_MESSAGE PRIMARY KEY (MESSAGE_ID),
    CONSTRAINT FK_CHAT_MESSAGE_CONVERSATION FOREIGN KEY (CONVERSATION_ID) REFERENCES CONVERSATION (CONVERSATION_ID),
    CONSTRAINT FK_CHAT_MESSAGE_SENDER FOREIGN KEY (SENDER_ID) REFERENCES MEMBERTBL (ID)
);


--==============================================================================
-- 9) BALANCE_TRANSACTION  (엔티티: com.chatservice.marketplace.wallet.domain.BalanceTransaction)
--    잔액 변동 내역. AMOUNT 는 부호 있는 변동량(증가 +, 감소 -). 삭제하지 않는다.
--==============================================================================
CREATE TABLE BALANCE_TRANSACTION (
    TRANSACTION_ID  NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    MEMBER_ID       VARCHAR2(255)   NOT NULL,
    TYPE            VARCHAR2(30)    NOT NULL,
    AMOUNT          NUMBER(15)      NOT NULL,
    BALANCE_AFTER   NUMBER(15)      NOT NULL,
    ORDER_ID        NUMBER(19),
    REQUEST_ID      VARCHAR2(64),
    CREATED_AT      TIMESTAMP(6)    NOT NULL,
    CONSTRAINT PK_BALANCE_TRANSACTION PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT FK_BALANCE_TX_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERTBL (ID),
    CONSTRAINT FK_BALANCE_TX_ORDER FOREIGN KEY (ORDER_ID) REFERENCES PURCHASE_ORDER (ORDER_ID),
    CONSTRAINT CK_BALANCE_TX_TYPE CHECK (TYPE IN ('CHARGE', 'PURCHASE', 'CANCEL_REFUND', 'REFUND', 'SALE_PAYOUT')),
    CONSTRAINT CK_BALANCE_TX_AMOUNT CHECK (AMOUNT <> 0),
    CONSTRAINT CK_BALANCE_TX_BALANCE_AFTER CHECK (BALANCE_AFTER >= 0)
);


--==============================================================================
-- 적재 검증(선택) — 9개 테이블이 보이면 정상.
--==============================================================================
-- SELECT TABLE_NAME FROM USER_TABLES
--  WHERE TABLE_NAME IN ('PRODUCT','WALLET','CONVERSATION','PRICE_OFFER','PURCHASE_ORDER',
--                       'SHIPMENT','REFUND_REQUEST','CHAT_MESSAGE','BALANCE_TRANSACTION')
--  ORDER BY TABLE_NAME;

COMMIT;
